title: Machine Learning Blogs
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/ml-blog" # the subpath of your site, e.g. /blog
url: "https://bitmask93.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Jithin J # add your name
author-img: david-freeman.jpg # add your photo
about-author: Machine Learning Engineer. Interested in Machine Learning and Deep Learning. # add description
social-github: bitmask93 # add your Github handle
social-linkedin: jithin-j-a5b662170 # add your Linkedin handle
social-email: jithinjayan1993@gmail.com # add your Email address

# Disqus
discus-identifier: jithin-1  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
